name: CI

on:
  push:
  pull_request:

jobs:
  verify-fred:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive

    # fred and scripts are subrepositories. They must be updated to match the release.
    - name: verify fred
      shell: bash
      run: |
        ./run-node.sh
        echo -e "export fredDir=\"$(realpath .)/fred\"\nexport freenetExtPath=\"$HOME/Freenet/freenet-ext.jar\"\nexport fcpHost=127.0.0.1\nexport fcpPort=9481\n" > "$HOME"/.freenetrc
        cat "$HOME"/.freenetrc
        cp "$HOME"/Freenet/freenet.jar ./wininstaller-innosetup/freenet.jar
        sudo apt-get install python3
        pip --install pyFreenet3
        cd ./scripts && ./verify-build --tag build01497 --online

