name: CI

on:
  push:
  pull_request:

jobs:
  verify-fred:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive

    # fred and scripts are subrepositories. They must be updated to match the release.
    - name: verify fred
      shell: bash
      run: |
        echo "remove too new Java"; sudo apt-get remove -y temurin-11-jdk temurin-17-jdk temurin-21-jdk
        echo "install python and java 8"; sudo apt-get install python3 temurin-8-jdk
        echo "update JAVA_HOME environment variable"; source /etc/environment; source /etc/profile; export JAVA_HOME=/usr/lib/jvm/temurin-8-jdk-amd64
        pip install pyFreenet3
        bash -x ./run-node.sh
        echo -e "export fredDir=\"$(realpath .)/fred\"\nexport freenetExtPath=\"$HOME/Freenet/freenet-ext.jar\"\nexport fcpHost=127.0.0.1\nexport fcpPort=9481\n" > "$HOME"/.freenetrc
        cp "$HOME"/Freenet/freenet.jar ./wininstaller-innosetup/freenet.jar
        wget https://www.hyphanet.org/assets/keyring.gpg && gpg --import keyring.gpg
        cd ./scripts && bash -x ./verify-build --tag build01497 --online ; cd -
        ./stop-node.sh

