name: CI

on:
  push:
  pull_request:

jobs:
  verify-fred:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # fred and scripts are subrepositories. They must be updated to match the release.
    - name: verify fred
      working-directory: ./scripts
      shell: bash
      run: |
        ./run-node.sh
        echo -e "export fredDir=\"$HOME\,/fred\\nexport freenetExtPath=\"$HOME\"/freenet-ext.jar\nexport fcpHost=127.0.0.1\nexport fcpPort=9481\n" > "$HOME"/.freenetrc
        cp freenet.jar "${HOME}"/wininstaller-innosetup/freenet.jar
        ./verify-build --tag build01497 --online

